name: Build EDK2 platforms

on:
  push: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config: 
          - platformname: RPi3
            dscfile: Platform/RaspberryPi/RPi3/RPi3.dsc
            arch: AARCH64
          - platformname: RPi4
            dscfile: Platform/RaspberryPi/RPi4/RPi4.dsc
            arch: AARCH64
          - platformname: ArmJuno
            dscfile: Platform/ARM/JunoPkg/ArmJuno.dsc
            arch: AARCH64
          - platformname: Sgi575
            dscfile: Platform/ARM/SgiPkg/Sgi575/Sgi575.dsc
            arch: AARCH64
          - platformname: BeagleBoard
            dscfile: Platform/BeagleBoard/BeagleBoardPkg/BeagleBoardPkg.dsc
            arch: ARM
          - platformname: FreedomU500VC707
            dscfile: Platform/SiFive/U5SeriesPkg/FreedomU500VC707Board/U500.dsc
            arch: RISCV64
          - platformname: FreedomU540HiFiveUnleashed
            dscfile: Platform/SiFive/U5SeriesPkg/FreedomU540HiFiveUnleashedBoard/U540.dsc
            arch: RISCV64
          - platformname: DeveloperBox
            dscfile: Platform/Socionext/DeveloperBox/DeveloperBox.dsc
            arch: AARCH64
          # - platformname: DeveloperBoxMm
          #   dscfile: Platform/Socionext/DeveloperBox/DeveloperBoxMm.dsc
          #   arch: AARCH64
        buildtarget: 
          - RELEASE
          - DEBUG
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y \
            uuid-dev \
            iasl \
            nasm \
            device-tree-compiler
          sudo apt-get clean

      - uses: actions/checkout@v2
        with:
          submodules: true 
      - run: git submodule foreach git submodule update --init --force --depth=1

      # Run the build commands
      - run: |
          export WORKSPACE=$PWD
          export PACKAGES_PATH=$PWD/edk2:$PWD/edk2-platforms:$PWD/edk2-non-osi
          . edk2/edksetup.sh
          make -C edk2/BaseTools
          build \
            -n 2 \
            -p edk2-platforms/${{ matrix.config.dscfile }} \
            -b ${{ matrix.buildtarget }} \
            -a ${{ matrix.config.arch }} \
            -t CLANGPDB

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.platformname }}_${{ matrix.config.arch }}_${{ matrix.buildtarget }}_GCC5
          path: Build/*/${{ matrix.buildtarget }}_CLANGPDB/FV/*.fd
